name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false    
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CONTENT_SSH_KEY }}
      - run: ssh-keyscan git.app.uib.no >> ~/.ssh/known_hosts
      - run: git submodule update --init --recursive
